//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using MinProjectMVC.Models.MetaData;

namespace MinProjectMVC.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(PeopleMetaData))]
    public partial class People
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public People()
        {
            this.Incomes = new HashSet<Incomes>();
        }
    
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public int PersonAge { get; set; }
        public bool PersonIsEmployed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incomes> Incomes { get; set; }
    }
}
